config/routes.rb
Siteua::Application.routes.draw do

  root :to => 'reports#index'
  
  match ':controller(/:action(/:id(.:format)))'

  resources :reports

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	DATE_FORMAT = '%d.%m.%Y'

	def index
		@date = (params[:date] ? Time.parse(params[:date]) : Time.now).strftime(DATE_FORMAT)
		a = AgentSiteua.new
		@stat = a.getstats(@date)
		@copypasts_ratio = cookies[:copypasts_ratio] || 100
		@rewrites_ratio = cookies[:rewrites_ratio] || 70

	end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<%= form_for 'reports', :url => reports_path, :html => {:class => 'form-horizontal'} do |f| %>
	<div class="control-group">
	  <label class="control-label" for="appendedInputButton">Месяц</label>
	  <div class="controls">
	    <div class="input-append">
	    	<%= text_field_tag :date, @date, :id => 'datepicker' %><%= f.submit('Go!', :class => 'btn') %>
	    </div>
	  </div>
	</div>
<% end %>
<hr>
<div class="well">
	<table class="table ">
		<thead>
			<th width="20%">Коэфф. (%)</th>
			<th width="20%">Тип новости</th>
			<th width="20%">Количество</th>
			<th width="20%">Сумма</th>
			<th width="10%">Катя</th>
			<th width="10%">Саша</th>
		</thead>
		<tbody>
			<tr>
				<td><%= text_field_tag :copypasts_ratio, @copypasts_ratio, :class => "input-mini" %></td>
				<td>Копипаст</td>
				<td><%= @stat.copypasts.size %></td>
				<td id="copypasts_sum"><%= sprintf("%0.2f",@stat.copypasts.inject(0) {|sum,r| sum+r[5].to_f}) %></td>
				<td><span class="label label-info" id="copypasts_sum_ratio">0</span></td>
				<td><span class="label label-info" id="copypasts_sum_ratio_p">0</span></td>
			</tr>
			<tr>
				<td><%= text_field_tag :rewrites_ratio, @rewrites_ratio, :class => "input-mini" %></td>
				<td>Рерайт</td>
				<td><%= @stat.rewrites.size %></td>
				<td id="rewrites_sum"><%= sprintf("%0.2f",@stat.rewrites.inject(0) {|sum,r| sum+r[5].to_f}) %></td>
				<td><span class="label label-info" id="rewrites_sum_ratio">0</span></td>
				<td><span class="label label-info" id="rewrites_sum_ratio_p">0</span></td>
			</tr>
			<tr>
				<th></th>
				<th>Всего</th>
				<th><%= @stat.rows.size %></th>
				<th><%= sprintf("%0.2f",@stat.rows.inject(0) {|sum,r| sum+r[5].to_f}) %></th>
				<td><span class="label label-info" id="sum_ratio">0</span></td>
				<td><span class="label label-info" id="sum_ratio_p">0</span></td>
			</tr>
		</tbody>
	</table>
</div>

<table class="table table-striped table-bordered table-condensed">
	<thead>
		<th>#</th>
		<% @stat.rows.headers.map do |header| %>
			<th><%= header %></th>
		<% end %>
	</thead>
	<tbody>
		
		<% (cnt=0) && @stat.rows.map do |row| %>
			<tr>
				<td><%= cnt+=1 %></td>
				<% @stat.rows.headers.size.times do |x| %>
					<td><%= row[x] %></td>
				<% end %>
			</tr>
		<% end %>
	</tbody>
</table>

<script type="text/javascript">
	function updateSum() {
		copypasts = $('#copypasts_sum').html();
		rewrites = $('#rewrites_sum').html();
		copypasts_ratio = $('#copypasts_ratio').val();
		rewrites_ratio = $('#rewrites_ratio').val();
		zp = Math.floor(copypasts*copypasts_ratio/100);
		zp_p = Math.floor(rewrites*rewrites_ratio/100);
		$.cookie('copypasts_ratio', copypasts_ratio);
		$.cookie('rewrites_ratio', rewrites_ratio);
		$('#copypasts_sum_ratio').html((zp).toFixed());
		$('#rewrites_sum_ratio').html((zp_p).toFixed());
		$('#sum_ratio').html((zp + zp_p).toFixed());
		$('#copypasts_sum_ratio_p').html(Math.floor(copypasts - zp));
		$('#rewrites_sum_ratio_p').html(Math.floor(rewrites - zp_p));
		$('#sum_ratio_p').html(Math.floor((copypasts - zp) + (rewrites - zp_p)));
	}
	$(document).ready(function(){
		updateSum();
		$('#copypasts_ratio, #rewrites_ratio').keyup(function(){
			updateSum();
		});
		$('#datepicker').datepicker({"format": "dd.mm.yyyy", "autoclose": true});
	})
</script>